using Microsoft.EntityFrameworkCore.Migrations;

namespace Customer_Onboarding.Migrations
{
    public partial class Initial : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "LocalGovtArea",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(nullable: true),
                    StateId = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_LocalGovtArea", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "State",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_State", x => x.Id);
                });

            migrationBuilder.InsertData(
                table: "LocalGovtArea",
                columns: new[] { "Id", "Name", "StateId" },
                values: new object[,]
                {
                    { 1, "Demsa", 1 },
                    { 512, "Ajaokuta", 25 },
                    { 513, "Adavi", 25 },
                    { 514, "Ankpa", 25 },
                    { 515, "Bassa", 25 },
                    { 516, "Dekina", 25 },
                    { 517, "Ibaji", 25 },
                    { 518, "Idah", 25 },
                    { 519, "Igalamela Odolu", 25 },
                    { 520, "Ijumu", 25 },
                    { 511, "Wudil", 24 },
                    { 521, "Kogi", 25 },
                    { 523, "Lokoja", 25 },
                    { 524, "Ofu", 25 },
                    { 525, "Mopa Muro", 25 },
                    { 526, "Ogori/Magongo", 25 },
                    { 527, "Okehi", 25 },
                    { 528, "Okene", 25 },
                    { 529, "Olamaboro", 25 },
                    { 530, "Omala", 25 },
                    { 531, "Yagba East", 25 },
                    { 522, "Kabba/Bunu", 25 },
                    { 532, "Yagba West", 25 },
                    { 510, "Warawa", 24 },
                    { 508, "Tudun Wada", 24 },
                    { 488, "Kano Municipal", 24 },
                    { 489, "Karaye", 24 },
                    { 490, "Kibiya", 24 },
                    { 491, "Kiru", 24 },
                    { 492, "Kumbotso", 24 },
                    { 493, "Kunchi", 24 },
                    { 494, "Kura", 24 },
                    { 495, "Madobi", 24 },
                    { 496, "Makoda", 24 },
                    { 509, "Ungogo", 24 },
                    { 497, "Minjibir", 24 },
                    { 499, "Rano", 24 },
                    { 500, "Rimin Gado", 24 },
                    { 501, "Rogo", 24 },
                    { 502, "Shanono", 24 },
                    { 503, "Takai", 24 },
                    { 504, "Sumaila", 24 },
                    { 505, "Tarauni", 24 },
                    { 506, "Tofa", 24 },
                    { 507, "Tsanyawa", 24 },
                    { 498, "Nasarawa", 24 },
                    { 533, "Aiyedire", 26 },
                    { 534, "Atakunmosa West", 26 },
                    { 535, "Atakunmosa East", 26 },
                    { 561, "Orolu", 26 },
                    { 562, "Osogbo", 26 },
                    { 563, "Gudu", 27 },
                    { 564, "Gwadabawa", 27 },
                    { 565, "Illela", 27 },
                    { 566, "Isa", 27 },
                    { 567, "Kebbe", 27 },
                    { 568, "Kware", 27 },
                    { 569, "Rabah", 27 },
                    { 560, "Oriade", 26 },
                    { 570, "Sabon Birni", 27 },
                    { 572, "Silame", 27 },
                    { 573, "Sokoto North", 27 },
                    { 574, "Sokoto South", 27 },
                    { 575, "Tambuwal", 27 },
                    { 576, "Tangaza", 27 },
                    { 577, "Tureta", 27 },
                    { 578, "Wamako", 27 },
                    { 579, "Wurno", 27 },
                    { 580, "Yabo", 27 },
                    { 571, "Shagari", 27 },
                    { 559, "Olorunda", 26 },
                    { 558, "Ola Oluwa", 26 },
                    { 557, "Odo Otin", 26 },
                    { 536, "Aiyedaade", 26 },
                    { 537, "Boluwaduro", 26 },
                    { 538, "Boripe", 26 },
                    { 539, "Ife East", 26 },
                    { 540, "Ede South", 26 },
                    { 541, "Ife North", 26 },
                    { 542, "Ede North", 26 },
                    { 543, "Ife South", 26 },
                    { 544, "Ejigbo", 26 },
                    { 545, "Ife Central", 26 },
                    { 546, "Ifedayo", 26 },
                    { 547, "Egbedore", 26 },
                    { 548, "Ila", 26 },
                    { 549, "Ifelodun", 26 },
                    { 550, "Ilesa East", 26 },
                    { 551, "Ilesa West", 26 },
                    { 552, "Irepodun", 26 },
                    { 553, "Irewole", 26 },
                    { 554, "Isokan", 26 },
                    { 555, "Iwo", 26 },
                    { 556, "Obokun", 26 },
                    { 487, "Kabo", 24 },
                    { 581, "Binji", 27 },
                    { 486, "Gwarzo", 24 },
                    { 484, "Gaya", 24 },
                    { 415, "Okigwe", 21 },
                    { 416, "Orlu", 21 },
                    { 417, "Orsu", 21 },
                    { 418, "Oru East", 21 },
                    { 419, "Oru West", 21 },
                    { 420, "Owerri Municipal", 21 },
                    { 421, "Owerri North", 21 },
                    { 422, "Unuimo", 21 },
                    { 423, "Owerri West", 21 },
                    { 414, "Ohaji/Egbema", 21 },
                    { 424, "Birnin Gwari", 22 },
                    { 426, "Giwa", 22 },
                    { 427, "Ikara", 22 },
                    { 428, "Igabi", 22 },
                    { 429, "Jaba", 22 },
                    { 430, "Jema'a", 22 },
                    { 431, "Kachia", 22 },
                    { 432, "Kaduna North", 22 },
                    { 433, "Kaduna South", 22 },
                    { 434, "Kagarko", 22 },
                    { 425, "Chikun", 22 },
                    { 435, "Kajuru", 22 },
                    { 413, "Oguta", 21 },
                    { 411, "Nwangele", 21 },
                    { 390, "Orelope", 20 },
                    { 391, "Ori Ire", 20 },
                    { 392, "Oyo", 20 },
                    { 393, "Oyo East", 20 },
                    { 394, "Saki East", 20 },
                    { 395, "Saki West", 20 },
                    { 396, "Surulere Oyo State", 20 },
                    { 397, "Aboh Mbaise", 21 },
                    { 398, "Ahiazu Mbaise", 21 },
                    { 412, "Obowo", 21 },
                    { 399, "Ehime Mbano", 21 },
                    { 401, "Ideato North", 21 },
                    { 402, "Ideato South", 21 },
                    { 403, "Ihitte/Uboma", 21 },
                    { 404, "Ikeduru", 21 },
                    { 405, "Isiala Mbano", 21 },
                    { 407, "Isu", 21 },
                    { 408, "Ngor Okpala", 21 },
                    { 409, "Njaba", 21 },
                    { 410, "Nkwerre", 21 },
                    { 400, "Ezinihitte", 21 },
                    { 436, "Kaura", 22 },
                    { 437, "Kauru", 22 },
                    { 438, "Kubau", 22 },
                    { 464, "Sakaba", 23 },
                    { 465, "Wasagu/Danko", 23 },
                    { 466, "Yauri", 23 },
                    { 467, "Zuru", 23 },
                    { 468, "Ajingi", 24 },
                    { 469, "Albasu", 24 },
                    { 470, "Bagwai", 24 },
                    { 471, "Bebeji", 24 },
                    { 472, "Bichi", 24 },
                    { 463, "Suru", 23 },
                    { 473, "Bunkure", 24 },
                    { 475, "Dambatta", 24 },
                    { 476, "Dawakin Kudu", 24 },
                    { 477, "Dawakin Tofa", 24 },
                    { 478, "Doguwa", 24 },
                    { 479, "Fagge", 24 },
                    { 480, "Gabasawa", 24 },
                    { 481, "Garko", 24 },
                    { 482, "Garun Mallam", 24 },
                    { 483, "Gezawa", 24 },
                    { 474, "Dala", 24 },
                    { 462, "Shanga", 23 },
                    { 461, "Ngaski", 23 },
                    { 460, "Maiyama", 23 },
                    { 439, "Kudan", 22 },
                    { 440, "Lere", 22 },
                    { 441, "Makarfi", 22 },
                    { 442, "Sabon Gari", 22 },
                    { 443, "Sanga", 22 },
                    { 444, "Soba", 22 },
                    { 445, "Zangon Kataf", 22 },
                    { 446, "Zaria", 22 },
                    { 447, "Aleiro", 23 },
                    { 448, "Argungu", 23 },
                    { 449, "Arewa Dandi", 23 },
                    { 450, "Augie", 23 },
                    { 451, "Bagudo", 23 },
                    { 452, "Birnin Kebbi", 23 },
                    { 453, "Bunza", 23 },
                    { 454, "Dandi", 23 },
                    { 455, "Fakai", 23 },
                    { 456, "Gwandu", 23 },
                    { 457, "Jega", 23 },
                    { 458, "Kalgo", 23 },
                    { 459, "Koko/Besse", 23 },
                    { 485, "Gwale", 24 },
                    { 389, "Ona Ara", 20 },
                    { 582, "Bodinga", 27 },
                    { 584, "Goronyo", 27 },
                    { 706, "Edu", 34 },
                    { 707, "Ilorin East", 34 },
                    { 708, "Ifelodun", 34 },
                    { 709, "Ilorin South", 34 },
                    { 710, "Ekiti Kwara State", 34 },
                    { 711, "Ilorin West", 34 },
                    { 712, "Irepodun", 34 },
                    { 713, "Isin", 34 },
                    { 714, "Kaiama", 34 },
                    { 705, "Baruten", 34 },
                    { 715, "Moro", 34 },
                    { 717, "Oke Ero", 34 },
                    { 718, "Oyun", 34 },
                    { 719, "Pategi", 34 },
                    { 720, "Akwanga", 35 },
                    { 721, "Awe", 35 },
                    { 722, "Doma", 35 },
                    { 723, "Karu", 35 },
                    { 724, "Keana", 35 },
                    { 725, "Keffi", 35 },
                    { 716, "Offa", 34 },
                    { 726, "Lafia", 35 },
                    { 704, "Asa", 34 },
                    { 702, "Sandamu", 33 },
                    { 682, "Faskari", 33 },
                    { 683, "Funtua", 33 },
                    { 684, "Ingawa", 33 },
                    { 685, "Jibia", 33 },
                    { 686, "Kafur", 33 },
                    { 687, "Kaita", 33 },
                    { 688, "Kankara", 33 },
                    { 689, "Kankia", 33 },
                    { 690, "Katsina", 33 },
                    { 703, "Zango", 33 },
                    { 691, "Kurfi", 33 },
                    { 693, "Mai'Adua", 33 },
                    { 694, "Malumfashi", 33 },
                    { 695, "Mani", 33 },
                    { 696, "Mashi", 33 },
                    { 697, "Matazu", 33 },
                    { 698, "Musawa", 33 },
                    { 699, "Rimi", 33 },
                    { 700, "Sabuwa", 33 },
                    { 701, "Safana", 33 },
                    { 692, "Kusada", 33 },
                    { 727, "Kokona", 35 },
                    { 728, "Nasarawa Egon", 35 },
                    { 729, "Nasarawa", 35 },
                    { 755, "Suleja", 36 },
                    { 756, "Tafa", 36 },
                    { 757, "Wushishi", 36 },
                    { 758, "Aba North", 37 },
                    { 759, "Arochukwu", 37 },
                    { 760, "Aba South", 37 },
                    { 761, "Bende", 37 },
                    { 762, "Isiala Ngwa North", 37 },
                    { 763, "Ikwuano", 37 },
                    { 754, "Shiroro", 36 },
                    { 764, "Isiala Ngwa South", 37 },
                    { 766, "Obi Ngwa", 37 },
                    { 767, "Ohafia", 37 },
                    { 768, "Osisioma", 37 },
                    { 769, "Ugwunagbo", 37 },
                    { 770, "Ukwa East", 37 },
                    { 771, "Ukwa West", 37 },
                    { 772, "Umuahia North", 37 },
                    { 773, "Umuahia South", 37 },
                    { 774, "Umu Nneochi", 37 },
                    { 765, "Isuikwuato", 37 },
                    { 753, "Rijau", 36 },
                    { 752, "Rafi", 36 },
                    { 751, "Paikoro", 36 },
                    { 730, "Obi", 35 },
                    { 731, "Toto", 35 },
                    { 732, "Wamba", 35 },
                    { 733, "Agaie", 36 },
                    { 734, "Agwara", 36 },
                    { 735, "Bida", 36 },
                    { 736, "Borgu", 36 },
                    { 737, "Bosso", 36 },
                    { 738, "Chanchaga", 36 },
                    { 739, "Edati", 36 },
                    { 740, "Gbako", 36 },
                    { 741, "Gurara", 36 },
                    { 742, "Katcha", 36 },
                    { 743, "Kontagora", 36 },
                    { 744, "Lapai", 36 },
                    { 745, "Lavun", 36 },
                    { 746, "Mariga", 36 },
                    { 747, "Magama", 36 },
                    { 748, "Mokwa", 36 },
                    { 749, "Mashegu", 36 },
                    { 750, "Moya", 36 },
                    { 681, "Dutsin Ma", 33 },
                    { 583, "Dange Shuni", 27 },
                    { 680, "Dutsi", 33 },
                    { 678, "Dan Musa", 33 },
                    { 609, "Jalingo", 29 },
                    { 610, "Karim Lamido", 29 },
                    { 611, "Kumi", 29 },
                    { 612, "Lau", 29 },
                    { 613, "Sardauna", 29 },
                    { 614, "Takum", 29 },
                    { 615, "Ussa", 29 },
                    { 616, "Wukari", 29 },
                    { 617, "Yorro", 29 },
                    { 608, "Ibi", 29 },
                    { 618, "Zing", 29 },
                    { 620, "Bursari", 30 },
                    { 621, "Damaturu", 30 },
                    { 622, "Fika", 30 },
                    { 623, "Fune", 30 },
                    { 624, "Geidam", 30 },
                    { 625, "Gujba", 30 },
                    { 626, "Gulani", 30 },
                    { 627, "Jakusko", 30 },
                    { 628, "Karasuwa", 30 },
                    { 619, "Bade", 30 },
                    { 629, "Machina", 30 },
                    { 607, "Gassol", 29 },
                    { 605, "Donga", 29 },
                    { 585, "Gada", 27 },
                    { 586, "Bokkos", 28 },
                    { 587, "Barkin Ladi", 28 },
                    { 588, "Bassa", 28 },
                    { 589, "Jos East", 28 },
                    { 590, "Jos North", 28 },
                    { 591, "Jos South", 28 },
                    { 592, "Kanam", 28 },
                    { 593, "Kanke", 28 },
                    { 606, "Gashaka", 29 },
                    { 594, "Langtang South", 28 },
                    { 596, "Mangu", 28 },
                    { 597, "Mikang", 28 },
                    { 598, "Pankshin", 28 },
                    { 599, "Qua'an Pan", 28 },
                    { 600, "Riyom", 28 },
                    { 601, "Shendam", 28 },
                    { 602, "Wase", 28 },
                    { 603, "Ardo Kola", 29 },
                    { 604, "Bali", 29 },
                    { 595, "Langtang North", 28 },
                    { 630, "Nangere", 30 },
                    { 631, "Nguru", 30 },
                    { 632, "Potiskum", 30 },
                    { 658, "Ibeju-Lekki", 32 },
                    { 659, "Ifako-Ijaiye", 32 },
                    { 660, "Ikeja", 32 },
                    { 661, "Ikorodu", 32 },
                    { 662, "Kosofe", 32 },
                    { 663, "Lagos Island", 32 },
                    { 664, "Mushin", 32 },
                    { 665, "Lagos Mainland", 32 },
                    { 666, "Ojo", 32 },
                    { 657, "Eti Osa", 32 },
                    { 667, "Oshodi-Isolo", 32 },
                    { 669, "Surulere Lagos State", 32 },
                    { 670, "Bakori", 33 },
                    { 671, "Batagarawa", 33 },
                    { 672, "Batsari", 33 },
                    { 673, "Baure", 33 },
                    { 674, "Bindawa", 33 },
                    { 675, "Charanchi", 33 },
                    { 676, "Danja", 33 },
                    { 677, "Dandume", 33 },
                    { 668, "Shomolu", 32 },
                    { 656, "Epe", 32 },
                    { 655, "Apapa", 32 },
                    { 654, "Badagry", 32 },
                    { 633, "Tarmuwa", 30 },
                    { 634, "Yunusari", 30 },
                    { 635, "Yusufari", 30 },
                    { 636, "Anka", 31 },
                    { 637, "Birnin Magaji/Kiyaw", 31 },
                    { 638, "Bakura", 31 },
                    { 639, "Bukkuyum", 31 },
                    { 640, "Bungudu", 31 },
                    { 641, "Gummi", 31 },
                    { 642, "Gusau", 31 },
                    { 643, "Kaura Namoda", 31 },
                    { 644, "Maradun", 31 },
                    { 645, "Shinkafi", 31 },
                    { 646, "Maru", 31 },
                    { 647, "Talata Mafara", 31 },
                    { 648, "Tsafe", 31 },
                    { 649, "Zurmi", 31 },
                    { 650, "Agege", 32 },
                    { 651, "Ajeromi-Ifelodun", 32 },
                    { 652, "Alimosho", 32 },
                    { 653, "Amuwo-Odofin", 32 },
                    { 679, "Daura", 33 },
                    { 388, "Oluyole", 20 },
                    { 406, "Mbaitoli", 21 },
                    { 386, "Ogo Oluwa", 20 },
                    { 123, "Etche", 6 },
                    { 124, "Gokana", 6 },
                    { 125, "Khana", 6 },
                    { 126, "Obio/Akpor", 6 },
                    { 127, "Ogba/Egbema/Ndoni", 6 },
                    { 128, "Ogu/Bolo", 6 },
                    { 129, "Okrika", 6 },
                    { 130, "Omuma", 6 },
                    { 131, "Opobo/Nkoro", 6 },
                    { 122, "Ikwerre", 6 },
                    { 132, "Oyigbo", 6 },
                    { 134, "Tai", 6 },
                    { 135, "Alkaleri", 7 },
                    { 136, "Bauchi", 7 },
                    { 137, "Bogoro", 7 },
                    { 138, "Damban", 7 },
                    { 139, "Darazo", 7 },
                    { 140, "Dass", 7 },
                    { 141, "Gamawa", 7 },
                    { 142, "Ganjuwa", 7 },
                    { 133, "Port Harcourt", 6 },
                    { 143, "Giade", 7 },
                    { 121, "Eleme", 6 },
                    { 119, "Degema", 6 },
                    { 99, "Akure South", 5 },
                    { 100, "Ese Odo", 5 },
                    { 101, "Idanre", 5 },
                    { 102, "Ifedore", 5 },
                    { 103, "Ilaje", 5 },
                    { 104, "Irele", 5 },
                    { 105, "Ile Oluji/Okeigbo", 5 },
                    { 106, "Odigbo", 5 },
                    { 107, "Okitipupa", 5 },
                    { 120, "Emuoha", 6 },
                    { 108, "Ondo West", 5 },
                    { 110, "Ondo East", 5 },
                    { 111, "Owo", 5 },
                    { 112, "Abua/Odual", 6 },
                    { 113, "Ahoada East", 6 },
                    { 114, "Ahoada West", 6 },
                    { 115, "Andoni", 6 },
                    { 116, "Akuku-Toru", 6 },
                    { 117, "Asari-Toru", 6 },
                    { 118, "Bonny", 6 },
                    { 109, "Ose", 5 },
                    { 144, "Itas/Gadau", 7 },
                    { 145, "Jama'are", 7 },
                    { 146, "Katagum", 7 },
                    { 172, "Okpokwu", 8 },
                    { 173, "Oturkpo", 8 },
                    { 174, "Tarka", 8 },
                    { 175, "Ukum", 8 },
                    { 387, "Olorunsogo", 20 },
                    { 177, "Vandeikya", 8 },
                    { 178, "Abadam", 9 },
                    { 179, "Askira/Uba", 9 },
                    { 180, "Bama", 9 },
                    { 171, "Oju", 8 },
                    { 181, "Bayo", 9 },
                    { 183, "Chibok", 9 },
                    { 184, "Damboa", 9 },
                    { 185, "Dikwa", 9 },
                    { 186, "Guzamala", 9 },
                    { 187, "Gubio", 9 },
                    { 188, "Hawul", 9 },
                    { 189, "Gwoza", 9 },
                    { 190, "Jere", 9 },
                    { 191, "Kaga", 9 },
                    { 182, "Biu", 9 },
                    { 170, "Ohimini", 8 },
                    { 169, "Ogbadibo", 8 },
                    { 168, "Obi", 8 },
                    { 147, "Kirfi", 7 },
                    { 148, "Misau", 7 },
                    { 149, "Ningi", 7 },
                    { 150, "Shira", 7 },
                    { 151, "Tafawa Balewa", 7 },
                    { 152, "Toro", 7 },
                    { 153, "Warji", 7 },
                    { 154, "Zaki", 7 },
                    { 155, "Agatu", 8 },
                    { 156, "Apa", 8 },
                    { 157, "Ado", 8 },
                    { 158, "Buruku", 8 },
                    { 159, "Gboko", 8 },
                    { 160, "Guma", 8 },
                    { 161, "Gwer East", 8 },
                    { 162, "Gwer West", 8 },
                    { 163, "Katsina-Ala", 8 },
                    { 164, "Konshisha", 8 },
                    { 165, "Kwande", 8 },
                    { 166, "Logo", 8 },
                    { 167, "Makurdi", 8 },
                    { 98, "Akure North", 5 },
                    { 192, "Kala/Balge", 9 },
                    { 97, "Akoko South-East", 5 },
                    { 95, "Akoko North-West", 5 },
                    { 26, "Essien Udim", 2 },
                    { 27, "Etim Ekpo", 2 },
                    { 28, "Etinan", 2 },
                    { 29, "Ibeno", 2 },
                    { 30, "Ibesikpo Asutan", 2 },
                    { 31, "Ibiono-Ibom", 2 },
                    { 32, "Ikot Abasi", 2 },
                    { 33, "Ika", 2 },
                    { 34, "Ikono", 2 },
                    { 25, "Esit Eket", 2 },
                    { 35, "Ikot Ekpene", 2 },
                    { 37, "Mkpat-Enin", 2 },
                    { 38, "Itu", 2 },
                    { 39, "Mbo", 2 },
                    { 40, "Nsit-Atai", 2 },
                    { 41, "Nsit-Ibom", 2 },
                    { 42, "Nsit-Ubium", 2 },
                    { 43, "Obot Akara", 2 },
                    { 44, "Okobo", 2 },
                    { 45, "Onna", 2 },
                    { 36, "Ini", 2 },
                    { 46, "Oron", 2 },
                    { 24, "Eket", 2 },
                    { 22, "Abak", 2 },
                    { 2, "Fufure", 1 },
                    { 3, "Ganye", 1 },
                    { 4, "Gayuk", 1 },
                    { 5, "Gombi", 1 },
                    { 6, "Grie", 1 },
                    { 7, "Hong", 1 },
                    { 8, "Jada", 1 },
                    { 9, "Larmurde", 1 },
                    { 10, "Madagali", 1 },
                    { 23, "Eastern Obolo", 2 },
                    { 11, "Maiha", 1 },
                    { 13, "Michika", 1 },
                    { 14, "Mubi North", 1 },
                    { 15, "Mubi South", 1 },
                    { 16, "Numan", 1 },
                    { 17, "Shelleng", 1 },
                    { 18, "Song", 1 },
                    { 19, "Toungo", 1 },
                    { 20, "Yola North", 1 },
                    { 21, "Yola South", 1 },
                    { 12, "Mayo Belwa", 1 },
                    { 47, "Udung-Uko", 2 },
                    { 48, "Ukanafun", 2 },
                    { 49, "Oruk Anam", 2 },
                    { 75, "Abeokuta South", 4 },
                    { 76, "Ado-Odo/Ota", 4 },
                    { 77, "Egbado North", 4 },
                    { 78, "Ewekoro", 4 },
                    { 79, "Egbado South", 4 },
                    { 80, "Ijebu North", 4 },
                    { 81, "Ijebu East", 4 },
                    { 82, "Ifo", 4 },
                    { 83, "Ijebu Ode", 4 },
                    { 74, "Abeokuta North", 4 },
                    { 84, "Ijebu North East", 4 },
                    { 86, "Ikenne", 4 },
                    { 87, "Ipokia", 4 },
                    { 88, "Odeda", 4 },
                    { 89, "Obafemi Owode", 4 },
                    { 90, "Odogbolu", 4 },
                    { 91, "Remo North", 4 },
                    { 92, "Ogun Waterside", 4 },
                    { 93, "Shagamu", 4 },
                    { 94, "Akoko North-East", 5 },
                    { 85, "Imeko Afon", 4 },
                    { 73, "Oyi", 3 },
                    { 72, "Orumba South", 3 },
                    { 71, "Orumba North", 3 },
                    { 50, "Uruan", 2 },
                    { 51, "Urue-Offong/Oruko", 2 },
                    { 52, "Uyo", 2 },
                    { 53, "Aguata", 3 },
                    { 54, "Anambra East", 3 },
                    { 55, "Anaocha", 3 },
                    { 56, "Awka North", 3 },
                    { 57, "Anambra West", 3 },
                    { 58, "Awka South", 3 },
                    { 59, "Ayamelum", 3 },
                    { 60, "Dunukofia", 3 },
                    { 61, "Ekwusigo", 3 },
                    { 62, "Idemili North", 3 },
                    { 63, "Idemili South", 3 },
                    { 64, "Ihiala", 3 },
                    { 65, "Njikoka", 3 },
                    { 66, "Nnewi North", 3 },
                    { 67, "Nnewi South", 3 },
                    { 68, "Ogbaru", 3 },
                    { 69, "Onitsha North", 3 },
                    { 70, "Onitsha South", 3 },
                    { 96, "Akoko South-West", 5 },
                    { 193, "Konduga", 9 },
                    { 176, "Ushongo", 8 },
                    { 195, "Kwaya Kusar", 9 },
                    { 317, "Oji River", 16 },
                    { 318, "Uzo Uwani", 16 },
                    { 319, "Udi", 16 },
                    { 320, "Abaji", 17 },
                    { 321, "Bwari", 17 },
                    { 322, "Gwagwalada", 17 },
                    { 323, "Kuje", 17 },
                    { 324, "Kwali", 17 },
                    { 325, "Municipal Area Council", 17 },
                    { 316, "Udenu", 16 },
                    { 326, "Akko", 18 },
                    { 328, "Billiri", 18 },
                    { 329, "Dukku", 18 },
                    { 330, "Funakaye", 18 },
                    { 331, "Gombe", 18 },
                    { 332, "Kaltungo", 18 },
                    { 333, "Kwami", 18 },
                    { 334, "Nafada", 18 },
                    { 335, "Shongom", 18 },
                    { 336, "Yamaltu/Deba", 18 },
                    { 327, "Balanga", 18 },
                    { 337, "Auyo", 19 },
                    { 315, "Nsukka", 16 },
                    { 313, "Nkanu East", 16 },
                    { 293, "Gbonyin", 15 },
                    { 294, "Ido Osi", 15 },
                    { 295, "Ijero", 15 },
                    { 296, "Ikere", 15 },
                    { 297, "Ilejemeje", 15 },
                    { 298, "Irepodun/Ifelodun", 15 },
                    { 299, "Ikole", 15 },
                    { 300, "Ise/Orun", 15 },
                    { 301, "Moba", 15 },
                    { 314, "Nkanu West", 16 },
                    { 302, "Oye", 15 },
                    { 304, "Aninri", 16 },
                    { 305, "Enugu East", 16 },
                    { 306, "Enugu North", 16 },
                    { 307, "Ezeagu", 16 },
                    { 308, "Enugu South", 16 },
                    { 194, "Kukawa", 9 },
                    { 310, "Igbo Eze North", 16 },
                    { 311, "Igbo Eze South", 16 },
                    { 312, "Isi Uzo", 16 },
                    { 303, "Awgu", 16 },
                    { 338, "Babura", 19 },
                    { 339, "Buji", 19 },
                    { 340, "Biriniwa", 19 },
                    { 366, "Atiba", 20 },
                    { 367, "Atisbo", 20 },
                    { 368, "Egbeda", 20 },
                    { 369, "Ibadan North", 20 },
                    { 370, "Ibadan North-East", 20 },
                    { 371, "Ibadan North-West", 20 },
                    { 372, "Ibadan South-East", 20 },
                    { 373, "Ibarapa Central", 20 },
                    { 374, "Ibadan South-West", 20 },
                    { 365, "Akinyele", 20 },
                    { 375, "Ibarapa East", 20 },
                    { 377, "Ibarapa North", 20 },
                    { 378, "Irepo", 20 },
                    { 379, "Iseyin", 20 },
                    { 380, "Itesiwaju", 20 },
                    { 381, "Iwajowa", 20 },
                    { 382, "Kajola", 20 },
                    { 383, "Lagelu", 20 },
                    { 384, "Ogbomosho North", 20 },
                    { 385, "Ogbomosho South", 20 },
                    { 376, "Ido", 20 },
                    { 364, "Afijio", 20 },
                    { 363, "Taura", 19 },
                    { 362, "Yankwashi", 19 },
                    { 341, "Birnin Kudu", 19 },
                    { 342, "Dutse", 19 },
                    { 343, "Gagarawa", 19 },
                    { 344, "Garki", 19 },
                    { 345, "Gumel", 19 },
                    { 346, "Guri", 19 },
                    { 347, "Gwaram", 19 },
                    { 348, "Gwiwa", 19 },
                    { 349, "Hadejia", 19 },
                    { 350, "Jahun", 19 },
                    { 351, "Kafin Hausa", 19 },
                    { 352, "Kazaure", 19 },
                    { 353, "Kiri Kasama", 19 },
                    { 354, "Kiyawa", 19 },
                    { 355, "Kaugama", 19 },
                    { 356, "Maigatari", 19 },
                    { 357, "Malam Madori", 19 },
                    { 358, "Miga", 19 },
                    { 359, "Sule Tankarkar", 19 },
                    { 360, "Roni", 19 },
                    { 361, "Ringim", 19 },
                    { 292, "Emure", 15 },
                    { 291, "Ekiti West", 15 },
                    { 309, "Igbo Etiti", 16 },
                    { 289, "Ekiti East", 15 },
                    { 220, "Calabar Municipal", 11 },
                    { 221, "Calabar South", 11 },
                    { 222, "Etung", 11 },
                    { 223, "Ikom", 11 },
                    { 290, "Ekiti South-West", 15 },
                    { 225, "Obubra", 11 },
                    { 226, "Obudu", 11 },
                    { 227, "Odukpani", 11 },
                    { 228, "Ogoja", 11 },
                    { 219, "Boki", 11 },
                    { 229, "Yakuur", 11 },
                    { 231, "Aniocha North", 12 },
                    { 232, "Aniocha South", 12 },
                    { 233, "Bomadi", 12 },
                    { 234, "Burutu", 12 },
                    { 235, "Ethiope West", 12 },
                    { 236, "Ethiope East", 12 },
                    { 237, "Ika North East", 12 },
                    { 238, "Ika South", 12 }
                });

            migrationBuilder.InsertData(
                table: "LocalGovtArea",
                columns: new[] { "Id", "Name", "StateId" },
                values: new object[,]
                {
                    { 239, "Isoko North", 12 },
                    { 230, "Yala", 11 },
                    { 240, "Isoko South", 12 },
                    { 218, "Biase", 11 },
                    { 216, "Bakassi", 11 },
                    { 196, "Mafa", 9 },
                    { 197, "Magumeri", 9 },
                    { 198, "Maiduguri", 9 },
                    { 199, "Mobbar", 9 },
                    { 200, "Marte", 9 },
                    { 201, "Monguno", 9 },
                    { 202, "Ngala", 9 },
                    { 203, "Nganzai", 9 },
                    { 204, "Shani", 9 },
                    { 217, "Bekwarra", 11 },
                    { 205, "Brass", 10 },
                    { 207, "Kolokuma/Opokuma", 10 },
                    { 208, "Nembe", 10 },
                    { 209, "Ogbia", 10 },
                    { 210, "Sagbama", 10 },
                    { 211, "Southern Ijaw", 10 },
                    { 212, "Yenagoa", 10 },
                    { 213, "Abi", 11 },
                    { 214, "Akamkpa", 11 },
                    { 215, "Akpabuyo", 11 },
                    { 206, "Ekeremor", 10 },
                    { 241, "Ndokwa East", 12 },
                    { 224, "Obanliku", 11 },
                    { 243, "Okpe", 12 },
                    { 269, "Akoko-Edo", 14 },
                    { 270, "Egor", 14 },
                    { 271, "Esan Central", 14 },
                    { 272, "Esan North-East", 14 },
                    { 273, "Esan South-East", 14 },
                    { 274, "Esan West", 14 },
                    { 275, "Etsako Central", 14 },
                    { 276, "Etsako East", 14 },
                    { 277, "Etsako West", 14 },
                    { 268, "Onicha", 13 },
                    { 278, "Igueben", 14 },
                    { 280, "Orhionmwon", 14 },
                    { 281, "Oredo", 14 },
                    { 282, "Ovia North-East", 14 },
                    { 242, "Ndokwa West", 12 },
                    { 284, "Owan East", 14 },
                    { 285, "Owan West", 14 },
                    { 286, "Uhunmwonde", 14 },
                    { 287, "Ado Ekiti", 15 },
                    { 288, "Efon", 15 },
                    { 279, "Ikpoba Okha", 14 },
                    { 267, "Ohaukwu", 13 },
                    { 283, "Ovia South-West", 14 },
                    { 265, "Izzi", 13 },
                    { 266, "Ohaozara", 13 },
                    { 244, "Oshimili North", 12 },
                    { 245, "Oshimili South", 12 },
                    { 246, "Patani", 12 },
                    { 248, "Udu", 12 },
                    { 249, "Ughelli North", 12 },
                    { 250, "Ukwuani", 12 },
                    { 251, "Ughelli South", 12 },
                    { 252, "Uvwie", 12 },
                    { 253, "Warri North", 12 },
                    { 254, "Warri South", 12 },
                    { 247, "Sapele", 12 },
                    { 256, "Abakaliki", 13 },
                    { 255, "Warri South West", 12 },
                    { 263, "Ivo", 13 },
                    { 261, "Ikwo", 13 },
                    { 260, "Ezza North", 13 },
                    { 262, "Ezza South", 13 },
                    { 259, "Afikpo South", 13 },
                    { 258, "Ebonyi", 13 },
                    { 257, "Afikpo North", 13 },
                    { 264, "Ishielu", 13 }
                });

            migrationBuilder.InsertData(
                table: "State",
                columns: new[] { "Id", "Name" },
                values: new object[,]
                {
                    { 22, "Kaduna" },
                    { 27, "Sokoto" },
                    { 23, "Kebbi" },
                    { 24, "Kano" },
                    { 25, "Kogi" },
                    { 26, "Osun" },
                    { 21, "Imo" },
                    { 31, "Zamfara" },
                    { 29, "Taraba" },
                    { 30, "Yobe" },
                    { 32, "Lagos" },
                    { 33, "Katsina" },
                    { 34, "Kwara" },
                    { 20, "Oyo" },
                    { 35, "Nasarawa" },
                    { 28, "Plateau" },
                    { 19, "Jigawa" },
                    { 7, "Bauchi" },
                    { 17, "Federal Capital Territory" },
                    { 36, "Niger" },
                    { 1, "Adamawa" },
                    { 2, "Akwa Ibom" },
                    { 3, "Anambra" },
                    { 4, "Ogun" },
                    { 5, "Ondo" },
                    { 6, "Rivers" },
                    { 18, "Gombe" },
                    { 8, "Benue" },
                    { 10, "Bayelsa" },
                    { 11, "Cross River" },
                    { 12, "Delta" },
                    { 13, "Ebonyi" },
                    { 14, "Edo" },
                    { 15, "Ekiti" },
                    { 16, "Enugu" },
                    { 9, "Borno" },
                    { 37, "Abia" }
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "LocalGovtArea");

            migrationBuilder.DropTable(
                name: "State");
        }
    }
}
